# Generated by Django 5.1.1 on 2024-09-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='is_active',
        ),
    ]
