# Generated by Django 5.1.1 on 2024-09-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sale_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_percent',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
